### ISSUE TITLE
Ergonomic improvement of the scroll bar (1.5)

### ISSUE THREAD

**Issue by dooclock** [oxymore-tech/baku#129]
**Is your feature request related to a problem? Please describe.**
"The photo flees when you click on it." "the shift puts text elements in blue".
The shift works in an extension direction but not reduction of the selection"...

**Describe the solution you'd like**

### Barre de lecture
(https://docs.google.com/document/d/1_cuojMoF3NqHHoARw0vanEIAPzPZwbe44sue2ujl7KM/edit?usp=sharing)
### Contexte :
Ecran de lecture de plan

#### Action :
L’utilisateur déplace le curseur de la barre de lecture.
#### Réaction :
Le liveview affiche en temps réel la frame en qualité réduite correspondant au déplacement du curseur.
La barre de miniature ne bouge pas avant que l’utilisateur est relaché son clic. Quand le clic est relâché la barre de miniature se cale au nouveau timecode.

#### Action :
L’utilisateur clique sur une miniature. 
#### Réaction :
L’image clique devient l’image active. Elle n’est pas déplacée au centre de la barre de miniature comme actuellement !
 
#### Action :
L’utilisateur clique droite/gauche du clavier. 
#### Réaction :
L’image est décalée vers la droite/gauche. Le liveview est mis à jour avec la nouvelle image active. Elle n’est pas déplacée au centre de la barre de miniature comme actuellement !

#### Action :
L’utilisateur sélectionne plusieurs miniatures avec shift + clic
#### Réaction :
Les autres miniatures sélectionnés ont une bordure  haute jaune 2 px
La zone de lecture de la barre de lecture change de longueur et occupe le temps correspondant aux frames choisies.
La zone de lecture de la barre de lecture est forcément sans espace vide.

**Additional context**
ui  +

**Comment by JBGamond** [comment]
https://akryum.github.io/vue-virtual-scroller/#/horizontal

Cliquer une une image affichée ne la centre pas.
Se placer sur une image non visible dans la scrollbar la centre et la sélectionne.
